name: Download
on:
  workflow_dispatch:
  workflow_call:
     
  
jobs:
  download:
    runs-on: ubuntu-latest
    if: always()
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Set ENV=branch-name
        id: extract-branch
        shell: bash
        run: echo "##$(echo ${GITHUB_REF#refs/heads/})"
      - name: Set up JDK 14
        id: setup-jdk
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache
        id: maven-cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Install
        if: steps.maven-cache.outputs.cache-hit != 'true'
        id: maven-install
        run: mvn install -DskipTests
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: Test.yml
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
      
      - uses: act10ns/slack@v1
        if: always()
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
