name: Container1 Atrifact
on:
  # schedule:
  # - cron: "0 21 * * 1"
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose the environment
        required: false
        default: "QA"
        options: 
        - "QA"
        - "UAT"
  workflow_call:
    inputs:
      environment:
        description: QA or UAT
        required: true
        type: string	
  
jobs:
  ChromeJoinDepo:
    runs-on: ubuntu-latest
    env:
      HEADLESS: true
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      SESSION: REGRESSION
      ENV: ${{ github.event.inputs.environment }} 
    steps:
      - uses: actions/checkout@v2
      - name: Set ENV=branch-name
        id: extract-branch
        shell: bash
        run: echo "##[set-env name=ENV;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Set up JDK 14
        id: setup-jdk
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache
        id: maven-cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Get Allure History
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
         ref: gh-pages
         path: gh-pages
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
