name: Container1 Atrifact
on:
  
  workflow_dispatch:
    

jobs:
  ChromeJoinDepo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set ENV=QA
        id: extract-branch
        shell: bash
        run: echo "$(echo ${GITHUB_REF#refs/heads/})"
      - name: Set up JDK 14
        id: setup-jdk
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache
        id: maven-cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Install
        if: steps.maven-cache.outputs.cache-hit != 'true'
        id: maven-install
        run: mvn clean install -DskipTests
      - name: Test in Linux
        id: report1
        shell: bash
        run: |
          mvn test -Dgroups=write -Dsurefire.suiteXmlFiles=testng.xml
      - uses: actions/upload-artifact@v1
        with:
          name: dipanjan
          path: dipanjan.txt
          
  
  TriggerEmail:
    runs-on: ubuntu-latest
    needs: [ChromeJoinDepo]
    steps:
      - uses: actions/checkout@v2
      - name: Set ENV=QA
        id: extract-branch
        shell: bash
        run: echo "##$(echo ${GITHUB_REF#refs/heads/})"
      - name: Set up JDK 14
        id: setup-jdk
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache
        id: maven-cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Install
        if: steps.maven-cache.outputs.cache-hit != 'true'
        id: maven-install
        run: mvn install -DskipTests
      - uses: actions/checkout@v2
      - name: Test in Linux
        id: report1
        shell: bash
        run: |
          mvn test -Dgroups=read -Dsurefire.suiteXmlFiles=testng.xml
      - uses: actions/download-artifact@v1
        with:
          name: dipanjan
      - run: cat dipanjan.txt
